title: Stock Goggles
email: stock-googles@proton.me
description: >-
  All data shown on this website is for informational purposes only
  and should not be relied upon to make trading or investing decisions.
baseurl: ""
url: "https://stock-goggles.github.io"

theme: minima

plugins:
  - jemoji
