title: Stock Goggles
email: stock.googles@proton.me
description: >-
  The information on this website is only for information only and does
  not constitute trading or investing advice. Investing involves risks,
  including the potential loss of your invested capital.
baseurl: ""
url: "https://stock-goggles.github.io"

theme: minima

plugins:
  - jemoji
