title: Stock Goggles
email: stock.googles@proton.me
description: >-
  The information on this website is only for information only and does not constitute trading or investing advice.
  Investing is risky, including the posibility of losing the entire invested capital.
baseurl: ""
url: "https://stock-goggles.github.io"

theme: minima

plugins:
  - jemoji
