title: Stunning Octo Goggles
email: your-email@example.com
description: >-
  All data shown on this website is for informational purposes only
  and should not be relied upon to make trading or investing decisions.
baseurl: ""
url: "https://stunning-octo-goggles.github.io"

theme: minima
